# Generated by Django 5.2.8 on 2025-11-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('author', models.CharField(max_length=15)),
                ('coverphoto', models.FileField(upload_to='meadia')),
                ('numberof_copies', models.IntegerField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.category')),
            ],
        ),
    ]
